### ISSUE TITLE
Bigquery destination tables partitionning

### ISSUE THREAD

**Issue by VinceLegendre** [z3z1ma/target-bigquery#12]
Hi guys! Love what you created here :clap: :fire: 
Regarding the configuration of destination tables, is there already a way to partition and/or cluster destination tables ?

I think it would be great to be able to specify :
 - the column to pick for partitioning (maybe only TIMESTAMP columns as a first step), which may be a metadata column by default
 - for a TIMESTAMP column, the frequency to use for partitioning

Happy to contribute :)

**Comment by z3z1ma** [comment]
There is not currently!

## Clustering
I think we should use table-key-properties to cluster ideally.

## Partitioning
Partitioning can be done on the replication-key if it exists falling back to ingestion time based partitioning.

We should have options for enabling/disabling this feature but I don't think the target should be responsible for the mapping. Also fixed schema sinks are both partitioned and clustered by default already. 

Would be happy to take a PR @VinceLegendre!
Let me know if you need any direction for this. I think it would be a valuable add to better utilize data available in the SCHEMA message.

**Comment by z3z1ma** [comment]
Resolved via latest commit which includes `cluster_on_key_properties` boolean to indicate if we should cluster on key_properties otherwise clusters on `_sdc_batched_at`. Partitioning granularity is now customizable too via `partition_granularity`. Certain higher volume sources may warrant "day" partitioning while low/mid volume sources are likely fine with "month" (default). Partitioning requires a certain amount of data per partition to be effective so we opt for a sane default here requesting the user configure higher granularity if needed on a per invocation/tap basis. 

We also released on pypi https://pypi.org/project/z3-target-bigquery/

**Comment by VinceLegendre** [comment]
Hi @z3z1ma , sorry for the delay in my answer, wasn't much available in the past weeks.

Some thoughts:
- I understand from [L169](https://github.com/z3z1ma/target-bigquery/blob/main/target_bigquery/core.py#L169) and [L309](https://github.com/z3z1ma/target-bigquery/blob/main/target_bigquery/core.py#L309) that the target table is created with a [combination of clustering and partition](https://cloud.google.com/bigquery/docs/clustered-tables#combining_clustered_and_partitioned_tables)
  - +1 on this, I find it great to partition on a meaningful time column and then cluster on key properties
  - quick question : are there downsides to use both clustering and partitioning on the same column by default? I only found this for now : ["However, partitioning requires BigQuery to maintain more metadata than with an unpartitioned table. As the number of partitions increases, the amount of metadata to maintain increases"](https://cloud.google.com/bigquery/docs/clustered-tables#combining_clustered_and_partitioned_tables)

- Would you agree that defining a custom column for time-based partitioning could be useful? Do you include this feature when saying *"we do cluster and partition but ideally we should use key_properties"* ?

  - I think that partitioning on *_sdc_batched_at* is a good data engineering practice (that suits us TBH), but may complexify data pipelines, for example when a reliable column such as *date_updated* exists in a SQL source.
