### ISSUE TITLE
Create tags when releasing new package versions

### ISSUE THREAD

**Issue by VinceLegendre** [z3z1ma/target-bigquery#14]
Hi @z3z1ma :wave: 
We'd like to be able to specify tags within the `pip_url` value in meltano configuration files.
I think it would increase stability on the users end :slightly_smiling_face: 

If the user base grows, maintaining a CHANGELOG.md would be awesome as well. No need to list each and every detail, but important breakthroughs and bugfixes. 

Would you be ok with using this process?

Best

**Comment by z3z1ma** [comment]
Agreed. I will add a few commits implementing `changie` for changelog management and cut a release afterwards. The support for `overwrite` and `upsert` strategies with binary on/off or per stream pattern matched enablement is certainly undersold 😆 .

I do release on pypi under the name `z3-target-bigquery` so you can already pin to specific versions via pypi but I will sync up the releases between there and here.
