### ISSUE TITLE
Load gets stuck with storage_write_api method 

### ISSUE THREAD

**Issue by VinceLegendre** [z3z1ma/target-bigquery#15]
I experienced problems when using the `storage_write_api` load method on several occasions :

- Everything works fine until records are all processed by the target :
- a confirmation message is sent by the target, e.g. **"_Target 'target-bigquery' completed reading 9770 lines of input_"**
- The target then tries to exit the bidirectional streams : "**_google.api_core.bidi | Thread-ConsumeBidirectionalStream exiting_**"
- Nothing happens after that

I may add that this behavior is not reproducible: no problem when restarting the same process a few minutes later.

Would you have any guess on what's causing the issue here @z3z1ma ? I have raised the logging level to DEBUG and looked into the codebase, but no concrete lead so far

**Comment by z3z1ma** [comment]
Honestly no unless we attach a debugger to the process. `python -m pdb -m target_bigquery.target:TargetBigQuery.cli ...` 

There might be a better way to do it too. But not sure. Let's leave this open for now and perhaps I can reproduce at some point.

**Comment by z3z1ma** [comment]
Closing this issue as we have pinned down and resolved the issue and the end to end integration tests now run multiple batches and multiple streams as insurance.

**Comment by emesar** [comment]
I see that this issue is allegedly resolved, but I'm observing the same symptoms intermittently using the `storage_write_api` load method. Any chance of a regression of the previous fix?
