### ISSUE TITLE
storage_write_api: choosing stream type for batch load jobs 

### ISSUE THREAD

**Issue by VinceLegendre** [z3z1ma/target-bigquery#16]
Some thoughts on picking the best stream type for batch ingestion :
 - According to [GCP documentation](https://cloud.google.com/bigquery/docs/write-api), [pending type](https://cloud.google.com/bigquery/docs/write-api#pending_type) is the recommanded choice for batch ingestion. It provides atomic operations and can be seen as an alternative to BQ load jobs, which we use when choosing `gcs_stage` mode.
 - I understand from the same documentation and from the explanation given in this project's README.md that the [commited type](https://cloud.google.com/bigquery/docs/write-api#committed_type) is offers an optimal read latency for streaming use cases.

My feeling is that the pending type would be the best choice when setting `options.storage_write_batch_mode` to `true`.

**Comment by VinceLegendre** [comment]
My bad, just saw that pending type is already in use : https://github.com/z3z1ma/target-bigquery/blob/main/target_bigquery/storage_write.py#L62.

I believe that the README should be corrected on this though. I can create a quick PR if that's ok with you @z3z1ma :slightly_smiling_face:

**Comment by z3z1ma** [comment]
Sure sounds good! Yes that's a mistranslation on my end. It should say that storage write batch mode uses pending streams as you'd expect. 😅

**Comment by VinceLegendre** [comment]
Dedicated PR #17
