### ISSUE TITLE
Offset error when using Storage Write API - batch mode

### ISSUE THREAD

**Issue by mattsax** [z3z1ma/target-bigquery#18]
I get the following error when I have more than one stream and using the Storage Write API on batch mode:

`google.api_core.exceptions.OutOfRange: 400 The offset is beyond stream, expected offset 0, received 2313`
I managed to reproduce the error by adding a second stream in the test data and using the batch mode:

```
OPTS = {
        "method": method,
        "denormalized": False,
        "generate_view": False,
        "batch_size": 2,  # force multiple batches
        "options": {
            'storage_write_batch_mode': True
        }
    }
```

I see two issues here: 

- I can see the error in the logs (raised by the subprocess), but the error isn't raised at main process level. Meltano then consider that the job succeeded.
- The offset that is sent to the API is stored at the Worker level. Each time a worker get a new job form the queue, it increments the offset using he size of the job: `offset += len(job.data.serialized_rows)`. But it doesn't work when the Worker is dealing with two different streams: when sending the data of the second stream, it will use the offset from the first stream. I think there would be an issue two when 2 Workers are sharing jobs of a single stream. May be the offset should be at Sink level?

**Comment by VinceLegendre** [comment]
+1 on this :+1: 

Solving this hierarchy issue between workers and sink should also solve https://github.com/z3z1ma/target-bigquery/issues/15

**Comment by z3z1ma** [comment]
@VinceLegendre @mattsax 
This should be solved as of the latest release. It also comes with significant logging / error bubbling improvements so it is not possible to have a worker fail and not notify the main thread + detailed logging of error.

Going to close this for now. If anything else comes up, feel free to open another issue but I suspect this is the fix we needed.
