### ISSUE TITLE
Key Error "Append Columns" -> Not included in target

### ISSUE THREAD

**Issue by SBurwash** [z3z1ma/target-bigquery#2]
Getting error `if not self.config["append_columns"]` when running using **denormalized** setting. 

I believe this is because config `append_columns` does not exist: https://github.com/z3z1ma/target-bigquery/blob/428f87f0ccf07e23488105f1b61f00828c908e48/target_bigquery/sinks.py#L243

**Comment by z3z1ma** [comment]
Resolved by PR #3 

You can technically include `append_columns` or any configuration in your meltano.yml whether or not it is specified by the target in its props but it is certainly an oversight. Thanks for flagging and for the PR.

Please open a followup issue if anything else comes up.
