### ISSUE TITLE
3.11 support?

### ISSUE THREAD

**Issue by apenney** [z3z1ma/target-bigquery#61]
Hi,

We're working on an upgrade from 3.9 to 3.11 right now and I realized that you have `python = "<3.11,>=3.8"` set.  I was wondering how difficult it would be to bump to <3.12?  I tried to do some local testing but I don't have access to BQ so it's hard to run the tests (I'm just some poor devops guy, not one of the devs!).

I can fire up a PR with the changes to poetry.lock/pyproject.toml, but I figured I'd check if it would be accepted as I can't run the tests.

**Comment by z3z1ma** [comment]
I can try it

**Comment by z3z1ma** [comment]
I was able to pin deps via `poetry` with `<3.12` which used to not work, meaning an upstream dep did not permit it. It seems we are at a point where all upstream deps permit it so we should be good! I pushed a release 0.6.8 so I am going to close this issue. Feel free to open a new more specific issue if any problem crops up.
