### ISSUE TITLE
`credentials_json` is not stored in the `.env` file

### ISSUE THREAD

**Issue by emiliemyth** [z3z1ma/target-bigquery#75]
`credentials_json` is not stored in the `.env` file

When I use 
`meltano config target-bigquery set credentials_json [value]`, 
it isn't storing the credentials in the .env file. Instead, it is plain text.

Desired outcome:
- Create `.env` if it doesn't exist
- Store it `credentials_json` in the `.env` file.

**Comment by z3z1ma** [comment]
I dont think I can fix this on my side. Maybe it needs a PR to the hub repo
